### ISSUE TITLE
[CI-Travis] Fermer les issues concernant Ci Travis

### ISSUE THREAD

**Issue by tdanel** [PyroTeam/robocup-pkg#120]

**Comment by vcoelen** [comment]
Désolé, je ferme l'issue : 
- Il vaut mieux passer en majeur les issues qui semblent importantes
- ou les commenter pour les faire progresser
- ou proposer des solutions pour ces issues
- Les issues doivent idéalement concerner des points précis (correction, amélioration, nouvelles fonctionnalités...), à mon avis
- Cette issue risque de vivre éternellement si on ne parvient pas à fermer toutes les issues ci-travis?
