### ISSUE TITLE
[common_lib]  Chrono : Implémentation clock_gettime() avec CLOCK_THREAD_CPUTIME_ID

### ISSUE THREAD

**Issue by ValentinVERGEZ** [PyroTeam/robocup-pkg#24]
> **vcoelen** said :
> A mon avis c'est plus CLOCK_THREAD_CPUTIME_ID qui t’intéresse, du coup le mieux serait de construire une classe similaire aux classe std::chrono::*_clock pour pouvoir l'utiliser dans ma classe Chrono, en s'assurant que c'est bien disponible sur nos versions (de noyau, compilateur, libc...?). Avec CLOCK_PROCESS_CPUTIME_ID, tu vas mesurer pour tous les threads donc même souci avec ROS, que clock().
> 
> C'est le problème de clock, la doc indique qu'elle renvoie un nombre de ticks, ça n'est pas directement lié au nombre de cycles CPU, c'est une valeur définie par le noyau par rapport à une seconde d'où la constante CLOCKS_PER_SEC.

**Comment by tdanel** [comment]
Issue réglée ?

**Comment by vcoelen** [comment]
Non

**Comment by ValentinVERGEZ** [comment]
A faire idéalement pendant notre phase de cleanup de l'été, ou à abandonner.
Vincent, t'en penses quoi ?
Je ne suis plus sûr d'en avoir l'utilité.

**Comment by vcoelen** [comment]
Pour moi, c'était une amélioration mineure, puisque je n'en ai pas l'utilité actuellement. A voir si d'autres en ont besoin. 
Pour le moment je n'ai pas d'algorithme multi-threadé, avec des besoins de mesure de temps.
Si on abandonne cette fonctionnalité, ça ne me dérange pas.

**Comment by ValentinVERGEZ** [comment]
A voir ce soir avec @tdanel

**Comment by ValentinVERGEZ** [comment]
Personne n'a réellement besoin de cette amélioration. On ne bosse pas encore avec des thread.
Je ferme l'issue.
