### ISSUE TITLE
[objectDetection] Correction et amélioration détection machines

### ISSUE THREAD

**Issue by ValentinVERGEZ** [PyroTeam/robocup-pkg#48]
### Trois choses
- La détection des machines doit être corrigée pour, au moins, fournir les mêmes résultats que précédemment;
- La détection des machines doit être améliorée pour plus de fiabilité;
- Il serait **TRES intéressant** d'obtenir le sens de la machine (input / ouput) avec la simple information de landmarks. Voir explication qui suit.
### Indication input / ouptut

Information qu'on peut obtenir à la volée à l'aide des ArTags ou sur mise à jour avec par exemple un service dédié. L’exécuteur de tâche pourrait corriger cette information quand il fait une exploration.  
Ce que je propose c'est de codifier l'angle de la machine.  

L'angle d'une machine serait définit modulo 2Pi. Avec un angle de 0 degrés, l'input pointe vers le bas, l'ouptut vers le haut. A 180 degrés, la machine est inversé, l'input pointe vers le haut, l'output vers le bas.
Et logiquement à 90° et 270°, l'input pointe à droite puis à gauche et inversement pour l'output.

Pour signaler qu'on ne sait RIEN de l'input / output, on peut donner un angle compris entre 2Pi et 3Pi (inutile d'aller jusqu'à 4Pi).

**Comment by ValentinVERGEZ** [comment]
Comme l’interprétation du landmarks sera un peu particulière, il sera intéressant d'avoir du code d'utilisation dans les libs commune.

J'en profite pour poser quelques idées : 
- getInputOutput : retournant deux points avec orientation représentant l'entrée et la sortie de la machine et l'orientation du robot pour leurs faire face. Cette fonction doit préciser si l'input / output est connue où si les deux points retournées représentent indiféremment sorties et entrées.
  - surcharge de la première fonction permettant de placer ces deux points à une distance donnée de la machine
  - construction de marker représentatif d'une machine avec l'input et l'output (pour rviz)

**Comment by vcoelen** [comment]
Concernant, l'indication Input/Output : ok pour le choix d'une configuration de la machine qui donne les entrées/sorties en fonction de l'orientation, avec une préférence pour une représentation entre -Pi et Pi.
Ensuite cette histoire de 3Pi à 4Pi, pour moi c'est du bidouillage, pour plusieurs raison : 
- On fait porter par un paramètre une information qui n'a pas de sens intuitif, donc nécessité de bien documenter, ce qui n'est pas notre point fort,
- On dénormalise nos angles, ce qui n'est pas propre, (et potentiellement oblige des nœuds qui n'ont pas besoin de cette info à quand même devoir normaliser les angles, ex grid_maker...)
- Pourquoi bidouiller quand c'est nos propres messages et qu'il suffit d'ajouter un paramètre pour ajouter l'information (ex un booléen, nommé au choix : isAngleOk, isOrientationValid, isEntryCorrect, isEntryFullyKnown... ou un mix)

Et Ok, pour les fonctions de calculs dans les libs communes. Mais ça devrait faire partie d'une autre issue. Et quitte à faire ce genre de libs, il faudrait en profiter pour construire une petite lib de calcul géométrique dans le plan (soit construite à la main, soit basée sur eigen, par exemple) et l'ajouter à geometry_utils.

**Comment by ValentinVERGEZ** [comment]
> Concernant, l'indication Input/Output : ok pour le choix d'une configuration de la machine qui donne les entrées/sorties en fonction de l'orientation, avec une préférence pour une représentation entre -Pi et Pi.  

OK

> Ensuite cette histoire de 3Pi à 4Pi, pour moi c'est du bidouillage, pour plusieurs raison :
> 
> On fait porter par un paramètre une information qui n'a pas de sens intuitif, donc nécessité de bien documenter, ce qui n'est pas notre point fort,
> On dénormalise nos angles, ce qui n'est pas propre, (et potentiellement oblige des nœuds qui n'ont pas besoin de cette info à quand même devoir normaliser les angles, ex grid_maker...)
> Pourquoi bidouiller quand c'est nos propres messages et qu'il suffit d'ajouter un paramètre pour ajouter l'information (ex un booléen, nommé au choix : isAngleOk, isOrientationValid, isEntryCorrect, isEntryFullyKnown... ou un mix)
> Et Ok, pour les fonctions de calculs dans les libs communes. Mais ça devrait faire partie d'une autre issue. Et quitte à faire ce genre de libs, il faudrait en profiter pour construire une petite lib de calcul géométrique dans le plan (soit construite à la main, soit basée sur eigen, par exemple) et l'ajouter à geometry_utils.

Au temps pour moi, je pensais naïvement que les landmarks étaient d'un format standard. Du coup je te rejoins.

J'ai ouvert l'issue pour pas oublier ce que j'avais en tête et proposer des choses. Il y a effectivement un découpage à faire.

**Comment by tdanel** [comment]
Est-ce que ce serait utile de définir un nouveau message pour les machines ? du style 

name -> std_msgs::string
area -> std_msgs::Int32
center -> geometry_msgs::Pose2D
input -> input 
-------id -> std_msgs::Int (artagID)
-------pose -> geometry_msgs::Pose2D
output -> output 
-------id -> std_msgs::Int (artagID)
-------pose -> geometry_msgs::Pose2D

**Comment by ValentinVERGEZ** [comment]
Oui pourquoi pas. Mais inutile de trimbaler des informations dérivées comme l'input ou l'output.
Et je ne pense pas que le name doivent apparaître dans les landmarks.

Et si on fait cet effort, il faudrait faire l'effort de faire le nouveau message et toute la migration en une PR.

**Comment by tdanel** [comment]
Question : Le changement d'angle doit se faire dans le landmarks_extraction_node ou dans le cartographie_node ? Je penche pour landmarks extraction puisqu'il est plus facile d'identifier un AR Tag à un segment.

**Comment by ValentinVERGEZ** [comment]
Aucune idée. J'aurais plutôt dit cartographie, mais l'un ou l'autre c'est
pareil pour moi

Le lun. 20 juin 2016 11:17, Thomas DANEL notifications@github.com a
écrit :

**Comment by tdanel** [comment]
Oui, comme ça on fait la fusion d'infos dans la carto ^^

**Comment by ValentinVERGEZ** [comment]
Si tu as déjà l'idée en tête, comme je n'en ai aucune, fonce !! :smile:

**Comment by tdanel** [comment]
Tiens, on rajoute les ids des AR Tags et le nom de la machine maintenant ??? ;)

**Comment by ValentinVERGEZ** [comment]
Juste l'ArTag, pas le nom :-P
Quand je disais non pour l'Input ou l'Ouput je parlais de la pose, pas de l'ID.

(T'as vu je m'en sors bien :trollface: )

**Comment by tdanel** [comment]
Fait, l'amélioration reste néanmoins un élément important de notre futur !
