### ISSUE TITLE
Normalisation namespace [AR_TRACK_ALVAR]

### ISSUE THREAD

**Issue by tdanel** [PyroTeam/robocup-pkg#66]

**Comment by ValentinVERGEZ** [comment]
ar_track_alvar est paramétrable et peut donc être lancé avec le frame_id qui va bien, à savoir du coup, celui de la caméra.
Même mieux, si par défaut il peut publier avec comme frame_id celui de l'image caméra ça serait top. A voir s'il ne fait pas lui-même les transformations (je n'espère pas sinon ça peut être problématique).

Je me l'assigne.

**Comment by ValentinVERGEZ** [comment]
Précisions.
Ar_track_alvar prend obligatoirement en argument le output_frame_id. Non seulement c'est le repère qui sera renseigné dans les messages, mais c'est aussi réellement le repère qui sera utilisé. Il doit exister et une transformation entre lui et le repère caméra doit exister. Ar_track_alvar fera une transformation pour placer ces markers.

Dans notre cas, l'idéal est donc que le repère utilisé soit le même que le repère caméra ou encore le repère robot. A voir ...

L'approche finale s'attend à ce que les informations soient dans le repère caméra.
En solution de contournement, on peut mettre un très gros message d'erreur dans l'approche finale si le frame_id n'est pas exactement celui attendu.
En solution définitive, faire la transformation nécessaire ...
