### ISSUE TITLE
Ajouter position actuelle du robot dans activity

### ISSUE THREAD

**Issue by SandraHage** [PyroTeam/robocup-pkg#79]
Le générateur a maintenant besoin de la position actuelle du robot,. Donc la meilleur façon de faire est de le rajouter la classe Odom ( fait pas Thomas normalement ) et qui sera envoyer via le Topic Activity au générateur

**Comment by vcoelen** [comment]
Pourquoi passer par le topic activity ?

**Comment by SandraHage** [comment]
ping Mme Vergez :p

**Comment by ValentinVERGEZ** [comment]
C'est une idée moisie que j'ai lancé et qui n'a pas été contredite.
En première réflexion, je pensais que le GT n'avait pas la possibilité de récupérer les infos des robots autrement que par les différents Exec. Taches. Mais c'est con. Avec la communication inter-robot, ou sans, le GT peut récupérer les infos de positions des différents robots sur différents topics.

Mais il faut/faudra récupérer au niveau du GT les différents namespaces des différents robots (sur base des paramètres).

**Comment by SandraHage** [comment]
Sinon, temporérement on peut récupérer la position de l'odométrie et puis on verra plus tard comment faire ça plus proprement. T'en penses quoi Vince?

**Comment by vcoelen** [comment]
Oui il est prévu dans la communication inter robot d'envoyer la position de tous les robots vers les autres robots et le générateur 
Et pas de soucis pour passer par l'odometrie, sur ma branche, il y a une classe pour ça dans les common.
